CREATE TABLE IF NOT EXISTS `user_login` (
    `id` CHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    `login` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `role` VARCHAR(255) NOT NULL
);